// Auto-generated by noise/import_kml.py from
// DenverMetro_v6_April-2025.kml (KBDU folder, 'Noise Abatement' placemarks).
// Edit import_kml.py and re-run instead of hand-editing this file.

export const NOISE_ZONES = [
  {
    name: 'Frasier Meadows',
    note: 'SE residential block — Frasier Meadows / Keewaydin neighborhood',
    polygon: [
      [40.014271, -105.216554],
      [39.99606, -105.216639],
      [39.996125, -105.189774],
      [40.014337, -105.189259],
      [40.014271, -105.216554],
    ],
  },
  {
    name: 'Valmont / East Pearl',
    note: 'Block immediately S of runway — 30th/Pearl/Valmont corridor',
    polygon: [
      [40.029612, -105.226334],
      [40.029579, -105.2223],
      [40.035034, -105.222257],
      [40.03373, -105.22632],
      [40.029612, -105.226334],
    ],
  },
  {
    name: 'Central & West Boulder',
    note: 'Downtown, University Hill, North Boulder, NCAR — main exclusion',
    polygon: [
      [40.060194, -105.244243],
      [40.062198, -105.247161],
      [40.087418, -105.28218],
      [40.08755, -105.300977],
      [39.996339, -105.299226],
      [39.985312, -105.286457],
      [39.985927, -105.22542],
      [39.996114, -105.225103],
      [40.014622, -105.225532],
      [40.014589, -105.253513],
      [40.029246, -105.253598],
      [40.029213, -105.234759],
      [40.034734, -105.234802],
      [40.03664, -105.239651],
      [40.036541, -105.258448],
      [40.05103, -105.258534],
      [40.05109, -105.244306],
      [40.060194, -105.244243],
    ],
  },
  {
    name: 'Gunbarrel / Heatherwood',
    note: 'NE residential — Gunbarrel and Heatherwood subdivisions',
    polygon: [
      [40.051047, -105.220582],
      [40.051042, -105.187214],
      [40.053208, -105.178206],
      [40.054982, -105.17812],
      [40.054982, -105.174773],
      [40.057966, -105.168751],
      [40.058059, -105.159244],
      [40.062251, -105.159405],
      [40.062384, -105.168621],
      [40.065738, -105.168681],
      [40.065697, -105.178488],
      [40.082438, -105.17855],
      [40.082455, -105.196255],
      [40.060304, -105.220521],
      [40.051047, -105.220582],
    ],
  },
]
