// populationRaster.js — Rasterize population density data into a Leaflet
// ImageOverlay. Reads the pre-built grid from population_density.json
// (generated by build_population_density.py).
//
// Usage:
//   import { loadPopulationDensity, rasterizePopulation } from './populationRaster'
//   const data = await loadPopulationDensity()
//   const overlay = rasterizePopulation(data)
//   // overlay = { dataUrl, latLngBounds } or null

// ── Color palette: transparent → pale yellow → orange → red → dark purple ──
// Sequential single-hue-to-multi-hue ramp typical for population density maps.
const POP_PALETTE = [
  [255, 255, 212],  // pale cream
  [254, 227, 145],  // light yellow
  [254, 196,  79],  // gold
  [254, 153,  41],  // orange
  [236, 112,  20],  // dark orange
  [204,  76,   2],  // burnt orange
  [153,  52,   4],  // brown
  [102,  37,   6],  // dark brown
]

function popPaletteLookup(t) {
  const c = Math.max(0, Math.min(1, t))
  const pos = c * (POP_PALETTE.length - 1)
  const i = pos | 0, f = pos - i
  const a = POP_PALETTE[i]
  const b = POP_PALETTE[Math.min(POP_PALETTE.length - 1, i + 1)]
  return [
    (a[0] + (b[0] - a[0]) * f) | 0,
    (a[1] + (b[1] - a[1]) * f) | 0,
    (a[2] + (b[2] - a[2]) * f) | 0,
  ]
}

let _cached = null

export async function loadPopulationDensity() {
  if (_cached) return _cached
  const resp = await fetch('/population_density.json')
  if (!resp.ok) throw new Error(`population_density.json: ${resp.status}`)
  _cached = await resp.json()
  return _cached
}

/**
 * Rasterize the population density grid into a canvas data URL.
 *
 * @param {Object} data  - The parsed population_density.json
 * @param {Object} [opts]
 * @param {number} [opts.logFloor=1]    - densities below this (people/km²) are transparent
 * @param {number} [opts.logCeil=15000] - density at which the palette saturates
 * @param {boolean} [opts.grayscale=false] - emit luminance (black→white) instead of
 *   the color palette. Pairs with a `screen` blend so dense areas glow like city
 *   lights on a dark basemap (or `multiply` to carve them in as shadow).
 * @returns {{ dataUrl: string, latLngBounds: [[number,number],[number,number]] } | null}
 */
export function rasterizePopulation(data, opts = {}) {
  if (!data || !data.grid) return null
  const { gridW, gridH, grid, bounds } = data
  const { latMin, latMax, lonMin, lonMax } = bounds

  const logFloor = opts.logFloor ?? 1
  const logCeil = opts.logCeil ?? 15000
  const grayscale = opts.grayscale ?? false

  const loL = Math.log(Math.max(1, logFloor))
  const hiL = Math.log(Math.max(2, logCeil))
  const span = hiL - loL

  // Build LUT
  const LUT_SIZE = 256
  const lutR = new Uint8Array(LUT_SIZE)
  const lutG = new Uint8Array(LUT_SIZE)
  const lutB = new Uint8Array(LUT_SIZE)
  for (let k = 0; k < LUT_SIZE; k++) {
    const [r, g, b] = popPaletteLookup(k / (LUT_SIZE - 1))
    lutR[k] = r; lutG[k] = g; lutB[k] = b
  }

  const canvas = document.createElement('canvas')
  canvas.width = gridW
  canvas.height = gridH
  const ctx = canvas.getContext('2d')
  const img = ctx.createImageData(gridW, gridH)
  const px = img.data

  let maxDensity = 0
  let filledCells = 0

  for (let row = 0; row < gridH; row++) {
    const gridRow = grid[row]
    if (!gridRow) continue
    for (let col = 0; col < gridW; col++) {
      const density = gridRow[col] || 0
      const idx = (row * gridW + col) * 4
      if (density <= logFloor) {
        px[idx + 3] = 0 // transparent
        continue
      }
      if (density > maxDensity) maxDensity = density
      filledCells++

      let s = (Math.log(density) - loL) / span
      if (s < 0) s = 0; else if (s > 1) s = 1
      if (grayscale) {
        // Pure luminance, dense → bright. Under a `screen` blend a black pixel
        // is a no-op and white adds full light, so density reads as a glow.
        const v = (s * 255) | 0
        px[idx + 0] = v; px[idx + 1] = v; px[idx + 2] = v
      } else {
        const k = (s * (LUT_SIZE - 1)) | 0
        px[idx + 0] = lutR[k]
        px[idx + 1] = lutG[k]
        px[idx + 2] = lutB[k]
      }
      // Alpha ramps from 0.3 at the low end to 0.7 at the high end —
      // translucent enough to see the basemap through, opaque enough
      // to read the density colors.
      const alpha = 0.3 + 0.4 * s
      px[idx + 3] = (alpha * 255) | 0
    }
  }

  ctx.putImageData(img, 0, 0)

  return {
    dataUrl: canvas.toDataURL('image/png'),
    latLngBounds: [[latMin, lonMin], [latMax, lonMax]],
    stats: { maxDensity, filledCells, gridW, gridH },
  }
}
